name: tabletop_gui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_signin_button: 1.0.0
  http: ^0.12.1
  firebase_auth: ^0.16.0
  google_sign_in: ^4.5.1
  url_launcher: ^5.4.10
  firebase_database: ^3.1.6
  cloud_firestore: ^0.13.6
  uuid: ^2.0.4
  rxdart: ^0.24.1
  audioplayers: ^0.15.1
  flutter_timer: ^0.0.6
  simple_animations: ^2.2.1

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/tabletop_logo.png
    - assets/images/download.jpg
    - assets/images/snake_game_thumbnail.png
    - assets/images/war_thumbnail.jpg
    - assets/images/fifteen_puzzle_thumbnail.jpg

    - assets/images/Felt.png
    - assets/images/cards/empty_of_empty.png
    - assets/images/cards/ace_of_clubs.png
    - assets/images/cards/ace_of_diamonds.png
    - assets/images/cards/ace_of_hearts.png
    - assets/images/cards/ace_of_spades.png
    - assets/images/cards/eight_of_clubs.png
    - assets/images/cards/eight_of_diamonds.png
    - assets/images/cards/eight_of_hearts.png
    - assets/images/cards/eight_of_spades.png
    - assets/images/cards/five_of_clubs.png
    - assets/images/cards/five_of_diamonds.png
    - assets/images/cards/five_of_hearts.png
    - assets/images/cards/five_of_spades.png
    - assets/images/cards/four_of_clubs.png
    - assets/images/cards/four_of_diamonds.png
    - assets/images/cards/four_of_hearts.png
    - assets/images/cards/four_of_spades.png
    - assets/images/cards/jack_of_clubs.png
    - assets/images/cards/jack_of_diamonds.png
    - assets/images/cards/jack_of_hearts.png
    - assets/images/cards/jack_of_spades.png
    - assets/images/cards/king_of_clubs.png
    - assets/images/cards/king_of_diamonds.png
    - assets/images/cards/king_of_hearts.png
    - assets/images/cards/king_of_spades.png
    - assets/images/cards/nine_of_clubs.png
    - assets/images/cards/nine_of_diamonds.png
    - assets/images/cards/nine_of_hearts.png
    - assets/images/cards/nine_of_spades.png
    - assets/images/cards/queen_of_clubs.png
    - assets/images/cards/queen_of_diamonds.png
    - assets/images/cards/queen_of_hearts.png
    - assets/images/cards/queen_of_spades.png
    - assets/images/cards/seven_of_clubs.png
    - assets/images/cards/seven_of_diamonds.png
    - assets/images/cards/seven_of_hearts.png
    - assets/images/cards/seven_of_spades.png
    - assets/images/cards/six_of_clubs.png
    - assets/images/cards/six_of_diamonds.png
    - assets/images/cards/six_of_hearts.png
    - assets/images/cards/six_of_spades.png
    - assets/images/cards/ten_of_clubs.png
    - assets/images/cards/ten_of_diamonds.png
    - assets/images/cards/ten_of_hearts.png
    - assets/images/cards/ten_of_spades.png
    - assets/images/cards/three_of_clubs.png
    - assets/images/cards/three_of_diamonds.png
    - assets/images/cards/three_of_hearts.png
    - assets/images/cards/three_of_spades.png
    - assets/images/cards/two_of_clubs.png
    - assets/images/cards/two_of_diamonds.png
    - assets/images/cards/two_of_hearts.png
    - assets/images/cards/two_of_spades.png

    - assets/audio/pickup_fruit.mp3
    - assets/audio/snake_death.mp3
    - assets/audio/snake_music.mp3
    - assets/audio/fifteen_tile_slide.mp3
    - assets/audio/playcard.mp3
    - assets/audio/shuffle.mp3
    - assets/audio/game_win.mp3

    - assets/images/apple_sprite.png
    - assets/images/snake_sprites/snake-tail-right.png
    - assets/images/snake_sprites/snake-tail-left.png
    - assets/images/snake_sprites/snake-tail-down.png
    - assets/images/snake_sprites/snake-tail-up.png
    - assets/images/snake_sprites/snake-head-right.png
    - assets/images/snake_sprites/snake-head-left.png
    - assets/images/snake_sprites/snake-head-down.png
    - assets/images/snake_sprites/snake-head-up.png
    - assets/images/snake_sprites/snake-body-down.png
    - assets/images/snake_sprites/snake-body-up.png
    - assets/images/snake_sprites/snake-body-right.png
    - assets/images/snake_sprites/snake-body-left.png
    - assets/images/snake_sprites/snake-corner-ld.png
    - assets/images/snake_sprites/snake-corner-lu.png
    - assets/images/snake_sprites/snake-corner-rd.png
    - assets/images/snake_sprites/snake-corner-ru.png
      # An image asset can vvvvvvvvvvvvvvvvvv to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
